// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClRaja7q0KT-3-kfOtxyeUqP_lbZUtmkE',
    appId: '1:530589257799:web:4d3248524288093d8be162',
    messagingSenderId: '530589257799',
    projectId: 'seodaang',
    authDomain: 'seodaang.firebaseapp.com',
    storageBucket: 'seodaang.appspot.com',
    measurementId: 'G-S4BSE6TN14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKjo1Akgna0E9m8q9NZvqSJU74KYxhsOw',
    appId: '1:530589257799:android:695cea5640b81c778be162',
    messagingSenderId: '530589257799',
    projectId: 'seodaang',
    storageBucket: 'seodaang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCzjskTLzIyTXmbHV0ihDhcUUdvIjp00',
    appId: '1:530589257799:ios:f9d176b3f209911a8be162',
    messagingSenderId: '530589257799',
    projectId: 'seodaang',
    storageBucket: 'seodaang.appspot.com',
    androidClientId:
        '530589257799-3ln0th5p1filtm19p5t1g9th47giatrp.apps.googleusercontent.com',
    iosClientId:
        '530589257799-c9jkm3fq069tshre096qnc1hpc1gior1.apps.googleusercontent.com',
    iosBundleId: 'com.seodaang.sdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkCzjskTLzIyTXmbHV0ihDhcUUdvIjp00',
    appId: '1:530589257799:ios:f9d176b3f209911a8be162',
    messagingSenderId: '530589257799',
    projectId: 'seodaang',
    storageBucket: 'seodaang.appspot.com',
    androidClientId:
        '530589257799-3ln0th5p1filtm19p5t1g9th47giatrp.apps.googleusercontent.com',
    iosClientId:
        '530589257799-c9jkm3fq069tshre096qnc1hpc1gior1.apps.googleusercontent.com',
    iosBundleId: 'com.seodaang.sdg',
  );
}
